CREATE OR REPLACE TYPE PROGRA2.ARTICULO_TYPE_COMPARACION
AS
  OBJECT
  (
    CODIGO      VARCHAR2 (20) ,
    DESCRIPCION VARCHAR2 (40) ,
    MAP MEMBER FUNCTION EQUALS RETURN NUMBER) NOT FINAL ;
    
  COMMIT;
    
CREATE OR REPLACE TYPE BODY PROGRA2.ARTICULO_TYPE_COMPARACION AS
  MAP MEMBER FUNCTION EQUALS RETURN NUMBER
  IS
    RETVAL NUMBER;
  BEGIN
    SELECT ora_hash(SELF.CODIGO||SELF.DESCRIPCION) INTO RETVAL FROM DUAL;
    RETURN RETVAL;
  
    END EQUALS;
  END;
  

    DECLARE
      GRUPO1 PROGRA2.ARTICULO_TYPE_COMPARACION;
      GRUPO2 PROGRA2.ARTICULO_TYPE_COMPARACION;
    BEGIN
      GRUPO1 := PROGRA2.ARTICULO_TYPE_COMPARACION('PRUEBA','DESCRIPCION');
      GRUPO2 := PROGRA2.ARTICULO_TYPE_COMPARACION('PRUEBA1','DESCRIPCION');
      IF GRUPO1 = GRUPO2 THEN
        DBMS_OUTPUT.PUT_LINE('SI SON IGUALES');
      ELSE
        DBMS_OUTPUT.PUT_LINE('NO SON IGUALES');
      END IF;
    END;
