-- Generado por Oracle SQL Developer Data Modeler 4.0.2.840
--   en:        2015-05-17 22:07:02 CST
--   sitio:      Oracle Database 12c
--   tipo:      Oracle Database 12c




CREATE OR REPLACE TYPE PROGRA2.UNIDADMEDIDA_TYPE ;
/

CREATE OR REPLACE TYPE PROGRA2.MARCA_TYPE ;
/

CREATE OR REPLACE TYPE PROGRA2.FAMILIA_TYPE ;
/

CREATE OR REPLACE TYPE PROGRA2.ARTICULOESTADO_TYPE ;
/

CREATE OR REPLACE TYPE PROGRA2.USUARIO_TYPE ;
/

CREATE OR REPLACE TYPE PROGRA2.EMPRESA_TYPE ;
/

CREATE OR REPLACE TYPE PROGRA2.MONEDA_TYPE ;
/

CREATE OR REPLACE TYPE PROGRA2.COTIZACIONESTADO ;
/

CREATE OR REPLACE TYPE PROGRA2.ARTICULO_TYPE ;
/

CREATE OR REPLACE TYPE PROGRA2.LISTAPRECIO_TYPE ;
/

CREATE OR REPLACE TYPE PROGRA2.PERMISO_TYPE ;
/

CREATE OR REPLACE TYPE PROGRA2.TIPOCAMBIO_TYPE ;
/

CREATE OR REPLACE TYPE PROGRA2.ESTADOTIPOCAMBIO_TYPE ;
/

CREATE OR REPLACE TYPE PROGRA2.ARTICULOESTADO_TYPE
AS
  OBJECT
  (
    DESCRIPCION VARCHAR2 (20) ) NOT FINAL ;
  /

CREATE OR REPLACE TYPE PROGRA2.REF_ARTICULO_TYPE
AS
  OBJECT
  (
    ARTICULO REF PROGRA2.ARTICULO_TYPE ) NOT FINAL ;
  /

CREATE OR REPLACE TYPE PROGRA2.LISTAARTICULOS
IS
  TABLE OF PROGRA2.REF_ARTICULO_TYPE ;
  /

CREATE OR REPLACE TYPE PROGRA2.ARTICULO_TYPE
AS
  OBJECT
  (
    CODIGO      VARCHAR2 (20) ,
    DESCRIPCION VARCHAR2 (40) ,
    UNDMEDIDA REF PROGRA2.UNIDADMEDIDA_TYPE ,
    CODMARCA REF PROGRA2.MARCA_TYPE ,
    FECHAREGISTRO DATE ,
    CODFAMILIA REF PROGRA2.FAMILIA_TYPE ,
    CODESTARTICULO REF PROGRA2.ARTICULOESTADO_TYPE ,
    CANTIDAD          NUMBER (10) ,
    CANTMAXIMA        NUMBER (10) ,
    CANTMINIMA        NUMBER (10) ,
    PRECIOMERCDOLARES NUMBER (17,2) ,
    FECHAACTPRECIO    DATE ,
    LISTA_COMPONENTES PROGRA2.LISTAARTICULOS ,
    CODUSERREGISTRO REF PROGRA2.USUARIO_TYPE ) NOT FINAL ;
  /

CREATE OR REPLACE TYPE PROGRA2.DIRECCION_TYPE
AS
  OBJECT
  (
    PAIS       VARCHAR2 (20) ,
    PROVINCIA  VARCHAR2 (20) ,
    CIUDAD     VARCHAR2 (20) ,
    APARPOSTAL VARCHAR2 (10) ,
    DETALLE1   VARCHAR2 (50) ,
    DETALLE2   VARCHAR2 (50) ) NOT FINAL ;
  /

CREATE OR REPLACE TYPE PROGRA2.TIPOCONTACTO_TYPE
AS
  OBJECT
  (
    NOMBRE VARCHAR2 (20) ) NOT FINAL ;
  /

CREATE OR REPLACE TYPE PROGRA2.CONTACTO_TYPE
AS
  OBJECT
  (
    DESCRIPCION VARCHAR2 (50) ,
    TIPOCONTACTO PROGRA2.TIPOCONTACTO_TYPE ) NOT FINAL ;
  /

CREATE OR REPLACE TYPE PROGRA2.LISTACONTACTOS
IS
  TABLE OF PROGRA2.CONTACTO_TYPE ;
  /

CREATE OR REPLACE TYPE PROGRA2.EMPRESA_TYPE
AS
  OBJECT
  (
    CEDULAJURIDICA  NUMBER (10) ,
    NOMBRECOMERCIAL VARCHAR2 (20) ,
    DIRECCION PROGRA2.DIRECCION_TYPE ,
    LISTA_CONTACTOS PROGRA2.LISTACONTACTOS ) NOT FINAL ;
  /

CREATE OR REPLACE TYPE PROGRA2.CLIENTE_TYPE UNDER PROGRA2.EMPRESA_TYPE ( ) NOT FINAL ;
/

CREATE OR REPLACE TYPE PROGRA2.COTIZACIONESTADO
AS
  OBJECT
  (
    DESCRIPCION VARCHAR2 (20) ) NOT FINAL ;
  /

CREATE OR REPLACE TYPE COTIZACION_HISTO_TYPE
AS
  OBJECT
  (
    NUMERO         NUMBER (10) ,
    FECHAREGISTRO  DATE ,
    EMPRESA        NUMBER (10) ,
    CONDICIONPAGO  VARCHAR2 (60) ,
    CONDICIONVENTA VARCHAR2 (60) ,
    VIGENCIA       VARCHAR2 (30) ,
    OBSERVACIONES  VARCHAR2 (10) ,
    MONEDA1        VARCHAR2 (10) ,
    CODESTADOCOTIZ VARCHAR2 (20) ,
    FECHA          DATE ) NOT FINAL ;
  /

CREATE OR REPLACE TYPE PROGRA2.COTIZACION_TYPE
AS
  OBJECT
  (
    NUMERO        NUMBER (10) ,
    FECHAREGISTRO DATE ,
    EMPRESA REF PROGRA2.EMPRESA_TYPE ,
    CONDICIONPAGO  VARCHAR2 (60) ,
    CONDICIONVENTA VARCHAR2 (60) ,
    VIGENCIA       VARCHAR2 (30) ,
    OBSERVACIONES  VARCHAR2 (10) ,
    MONEDA1 REF PROGRA2.MONEDA_TYPE ,
    CODESTADOCOTIZ REF PROGRA2.COTIZACIONESTADO ,
    FECHA DATE ,
    LISTA_ARTIC_COTIZADOS PROGRA2.LISTAARTICULOS ) NOT FINAL ;
  /

CREATE OR REPLACE TYPE PROGRA2.ESTADOTIPOCAMBIO_TYPE
AS
  OBJECT
  (
    NOMBRE VARCHAR2 (1) ) NOT FINAL ;
  /

CREATE OR REPLACE TYPE PROGRA2.EVENTO_TYPE
AS
  OBJECT
  (
    FECHA       DATE ,
    DESCRIPCION VARCHAR2 (75) ,
    USUARIO REF PROGRA2.USUARIO_TYPE ) NOT FINAL ;
  /

CREATE OR REPLACE TYPE PROGRA2.LINEAFACTURA_TYPE
AS
  OBJECT
  (
    ARTICULO REF PROGRA2.ARTICULO_TYPE ,
    PRECIO   NUMBER (17,2) ,
    CANTIDAD NUMBER (10) ) NOT FINAL ;
  /

CREATE OR REPLACE TYPE PROGRA2.LISTALINEASFACTURA
IS
  TABLE OF PROGRA2.LINEAFACTURA_TYPE ;
  /

CREATE OR REPLACE TYPE PROGRA2.FACTURACOMPRAS_TYPE
AS
  OBJECT
  (
    CODIGO      NUMBER (10) ,
    FECCOMPRA   DATE ,
    FECREGISTRO DATE ,
    LISTA_LINEASFACTURA PROGRA2.LISTALINEASFACTURA ,
    CODUSERREGISTRO REF PROGRA2.USUARIO_TYPE ) NOT FINAL ;
  /

CREATE OR REPLACE TYPE PROGRA2.FAMILIA_TYPE
AS
  OBJECT
  (
    DESCRIPCION    VARCHAR2 (40) ,
    PORCIMPACOMPRA NUMBER (3) ) NOT FINAL ;
  /

CREATE OR REPLACE TYPE PROGRA2.REF_TIPO_CAMBIO_TYPE
AS
  OBJECT
  (
    TIPO_CAMBIO REF PROGRA2.TIPOCAMBIO_TYPE ) NOT FINAL ;
  /

CREATE OR REPLACE TYPE PROGRA2.LISTATIPOCAMBIOS
IS
  TABLE OF PROGRA2.REF_TIPO_CAMBIO_TYPE ;
  /

CREATE OR REPLACE TYPE PROGRA2.INDICEECONOMICO_TYPE
AS
  OBJECT
  (
    DESCRIPCION      VARCHAR2 (20) ,
    NUMVALORESREALES NUMBER (10) ,
    NUMMESES         NUMBER (10) ,
    FAMILIA PROGRA2.FAMILIA_TYPE ,
    LISTA_TIPOCAMBIOS PROGRA2.LISTATIPOCAMBIOS ) NOT FINAL ;
  /

CREATE OR REPLACE TYPE PROGRA2.LISTAPRECIO_TYPE
AS
  OBJECT
  (
    DESCRIPCION VARCHAR2 (40) ,
    GASTOADMIN  NUMBER (3) ,
    GASTOOTROS  NUMBER (3) ,
    UTILIDAD    NUMBER (3) ,
    LISTA_ARTICULOS PROGRA2.LISTAARTICULOS ) NOT FINAL ;
  /

CREATE OR REPLACE TYPE PROGRA2.MARCA_TYPE
AS
  OBJECT
  (
    DESCRIPCION VARCHAR2 (20) ) NOT FINAL ;
  /

CREATE OR REPLACE TYPE PROGRA2.MONEDA_TYPE
AS
  OBJECT
  (
    DESCRIPCION VARCHAR2 (10) ) NOT FINAL ;
  /

CREATE OR REPLACE TYPE PROGRA2.PERMISO_TYPE
AS
  OBJECT
  (
    DESCRIPCION VARCHAR2 (20) ,
    FINAL CONSTRUCTOR
  FUNCTION PERMISO_TYPE(
      DESCRIPCION IN VARCHAR2 )
    RETURN SELF
  AS
    RESULT ) NOT FINAL ;
  /

CREATE OR REPLACE TYPE PROGRA2.PROVEEDOR_TYPE UNDER PROGRA2.EMPRESA_TYPE ( ) NOT FINAL ;
/

CREATE OR REPLACE TYPE PROGRA2.PROYECCION_TYPE
AS
  OBJECT
  (
    FECHA DATE ,
    ARTICULO REF PROGRA2.ARTICULO_TYPE ,
    LISTAPRECIO REF PROGRA2.LISTAPRECIO_TYPE ,
    TIPOCAMBIOPROYECT        NUMBER (17,2) ,
    PRECIOMERCDOLARESPROYECT NUMBER (17,2) ) NOT FINAL ;
  /

CREATE OR REPLACE TYPE PROGRA2.REF_PERMISO_TYPE
AS
  OBJECT
  (
    PERMISO REF PROGRA2.PERMISO_TYPE ) NOT FINAL ;
  /

CREATE OR REPLACE TYPE PROGRA2.TIPOCAMBIO_TYPE
AS
  OBJECT
  (
    FECHA DATE ,
    MONEDA_A REF PROGRA2.MONEDA_TYPE ,
    MONEDA_B REF PROGRA2.MONEDA_TYPE ,
    MONTO NUMBER (17,2) ,
    ESTADO REF PROGRA2.ESTADOTIPOCAMBIO_TYPE ) NOT FINAL ;
  /

CREATE OR REPLACE TYPE PROGRA2.UNIDADMEDIDA_TYPE
AS
  OBJECT
  (
    DESCRIPCION VARCHAR2 (40) ) NOT FINAL ;
  /

CREATE OR REPLACE TYPE PROGRA2.LISTAPERMISOS
IS
  TABLE OF PROGRA2.REF_PERMISO_TYPE ;
  /

CREATE OR REPLACE TYPE PROGRA2.USUARIO_TYPE
AS
  OBJECT
  (
    NOMBRE VARCHAR2 (10) ,
    CLAVE  VARCHAR2 (10) ,
    LISTA_PERMISOS PROGRA2.LISTAPERMISOS ) NOT FINAL ;
  /

CREATE OR REPLACE TYPE LISTAARTICULOSEMB
IS
  TABLE OF PROGRA2.ARTICULO_TYPE ;
  /

CREATE TABLE PROGRA2.ARTICULOS_TABLE OF PROGRA2.ARTICULO_TYPE
  (
    CODIGO NOT NULL ,
    CONSTRAINT ARTICULOS_TABLE_PK PRIMARY KEY ( CODIGO )
  )
  PCTFREE 10 PCTUSED 40 TABLESPACE PROYECTO LOGGING STORAGE
  (
    INITIAL 1048576 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  NESTED TABLE LISTA_COMPONENTES STORE AS LISTA_COMPONENTES ;


CREATE OR REPLACE PROCEDURE PROGRA2.SP_ELIMINARARTICULO (V_CODIGO IN  VARCHAR) 
IS   
BEGIN   
DELETE FROM ARTICULOS_TABLE 
WHERE CODIGO = V_CODIGO;
END;
/


CREATE OR REPLACE PROCEDURE PROGRA2.SP_ELIMINARCOMPONENTE (V_CODIGOART IN  VARCHAR,V_CODIGOCOMP IN  VARCHAR) 
IS
BEGIN

DELETE FROM TABLE(SELECT LISTA_COMPONENTES FROM ARTICULOS_TABLE WHERE CODIGO = V_CODIGOART) WHERE 
(SELECT DEREF(ARTICULO).CODIGO AS COD FROM TABLE (SELECT LISTA_COMPONENTES FROM ARTICULOS_TABLE WHERE CODIGO = V_CODIGOART)) = V_CODIGOCOMP;

END;
/

CREATE TABLE PROGRA2.UNIDADES_MEDIDAS_TABLE OF PROGRA2.UNIDADMEDIDA_TYPE
  (
    DESCRIPCION NOT NULL
  )
  PCTFREE 10 PCTUSED 40 TABLESPACE PROYECTO LOGGING STORAGE
  (
    INITIAL 1048576 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  ) ;

CREATE TABLE PROGRA2.MARCAS_TABLE OF PROGRA2.MARCA_TYPE
  (
    DESCRIPCION NOT NULL ,
    CONSTRAINT MARCAS_TABLE_PK PRIMARY KEY ( DESCRIPCION )
  )
  PCTFREE 10 PCTUSED 40 TABLESPACE PROYECTO LOGGING STORAGE
  (
    INITIAL 1048576 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  ) ;

CREATE TABLE PROGRA2.FAMILIAS_TABLE OF PROGRA2.FAMILIA_TYPE
  (
    DESCRIPCION NOT NULL ,
    CONSTRAINT FAMILIAS_TABLE_PK PRIMARY KEY ( DESCRIPCION )
  )
  PCTFREE 10 PCTUSED 40 TABLESPACE PROYECTO LOGGING STORAGE
  (
    INITIAL 1048576 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  ) ;

CREATE TABLE PROGRA2.ARTICULOESTADOS OF PROGRA2.ARTICULOESTADO_TYPE
  (
    DESCRIPCION NOT NULL ,
    CONSTRAINT ARTICULOESTADOS_PK PRIMARY KEY ( DESCRIPCION )
  )
  PCTFREE 10 PCTUSED 40 TABLESPACE PROYECTO LOGGING STORAGE
  (
    INITIAL 1048576 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  ) ;

CREATE TABLE PROGRA2.USUARIOS_TABLE OF PROGRA2.USUARIO_TYPE
  (
    NOMBRE NOT NULL ,
    CONSTRAINT USUARIOS_TABLE_PK PRIMARY KEY ( NOMBRE )
  )
  PCTFREE 10 PCTUSED 40 TABLESPACE PROYECTO LOGGING STORAGE
  (
    INITIAL 1048576 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  NESTED TABLE LISTA_PERMISOS STORE AS LISTA_PERMISOS ;


CREATE OR REPLACE PROCEDURE PROGRA2.SP_INSERTARARTICULO (V_CODIGO IN  VARCHAR,V_DESCRIPCION IN  VARCHAR,V_MARCA IN  VARCHAR,V_FAMILIA IN  VARCHAR,
                                                V_CANTIDAD IN  NUMBER,V_CANTMAXIMA IN  NUMBER,V_CANTMINIMA IN  NUMBER,V_PRECIO IN  NUMBER) 
IS
BEGIN   
   INSERT INTO ARTICULOS_TABLE 
   VALUES(V_CODIGO,V_DESCRIPCION,
(SELECT REF(P1) FROM UNIDADES_MEDIDAS_TABLE P1
        where DESCRIPCION = 'UN'),
      (SELECT REF(P2) FROM MARCAS_TABLE P2
        where DESCRIPCION = V_MARCA),
        SYSDATE, 
        (SELECT REF(P3) FROM FAMILIAS_TABLE P3
        where DESCRIPCION = V_FAMILIA),
        (SELECT REF(P4) FROM ARTICULOESTADOS P4
        where DESCRIPCION = 'ACTIVO'),V_CANTIDAD,V_CANTMAXIMA,V_CANTMINIMA,V_PRECIO,SYSDATE,LISTAARTICULOS(),
        (SELECT REF(P5) FROM USUARIOS_TABLE P5
        where NOMBRE = 'ADMIN')
);
END;
/


CREATE OR REPLACE PROCEDURE PROGRA2.SP_INSERTARCOMPONENTE (V_CODIGOART IN  VARCHAR,V_CODIGOCOMP IN  VARCHAR) 
IS
BEGIN   
INSERT INTO TABLE (SELECT LISTA_COMPONENTES FROM ARTICULOS_TABLE where CODIGO = V_CODIGOART) VALUES
((
      (SELECT REF(A) FROM ARTICULOS_TABLE A
        WHERE CODIGO = V_CODIGOCOMP)
      )
);
    
END;
/


CREATE OR REPLACE PROCEDURE PROGRA2.SP_MODIFICARARTICULO (V_CODIGO IN  VARCHAR,V_PRECIO IN  NUMBER) 
IS   
BEGIN   
UPDATE ARTICULOS_TABLE 
SET PRECIOMERCDOLARES = V_PRECIO,
    FECHAACTPRECIO = SYSDATE
WHERE CODIGO = V_CODIGO;
END;
/

CREATE TABLE PROGRA2.COTIZACION_HISTO_TABLE OF COTIZACION_HISTO_TYPE
  (
    NUMERO NOT NULL
  )
  LOGGING ;

CREATE TABLE PROGRA2.COTIZACION_TABLE OF PROGRA2.COTIZACION_TYPE
  (
    NUMERO NOT NULL ,
    CONSTRAINT COTIZACION_TABLE_PK PRIMARY KEY ( NUMERO )
  )
  PCTFREE 10 PCTUSED 40 TABLESPACE PROYECTO LOGGING STORAGE
  (
    INITIAL 1048576 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  NESTED TABLE LISTA_ARTIC_COTIZADOS STORE AS LISTA_ARTIC_COTIZADOS ;

CREATE TABLE PROGRA2.EMPRESAS_TABLE OF PROGRA2.EMPRESA_TYPE
  (
    CEDULAJURIDICA NOT NULL ,
    CONSTRAINT EMPRESAS_TABLE_PK PRIMARY KEY ( CEDULAJURIDICA )
  )
  PCTFREE 10 PCTUSED 40 TABLESPACE PROYECTO LOGGING STORAGE
  (
    INITIAL 1048576 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  NESTED TABLE LISTA_CONTACTOS STORE AS LISTA_CONTACTOS ;

CREATE TABLE PROGRA2.ESTADOS_COTIZACIONES_TABLE OF PROGRA2.COTIZACIONESTADO
  (
    DESCRIPCION NOT NULL ,
    CONSTRAINT ESTADOS_COTIZACIONES_TABLE_PK PRIMARY KEY ( DESCRIPCION )
  )
  PCTFREE 10 PCTUSED 40 TABLESPACE PROYECTO LOGGING STORAGE
  (
    INITIAL 1048576 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  ) ;

CREATE TABLE PROGRA2.ESTADOS_TIPO_CAMBIO_TABLE OF PROGRA2.ESTADOTIPOCAMBIO_TYPE
  (
    NOMBRE NOT NULL ,
    CONSTRAINT ESTADOS_TIPO_CAMBIO_TABLE_PK PRIMARY KEY ( NOMBRE )
  )
  PCTFREE 10 PCTUSED 40 TABLESPACE PROYECTO LOGGING STORAGE
  (
    INITIAL 1048576 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  ) ;

CREATE TABLE PROGRA2.EVENTOS_TABLE OF PROGRA2.EVENTO_TYPE
  (
    FECHA NOT NULL ,
    CONSTRAINT EVENTOS_TABLE_PK PRIMARY KEY ( FECHA )
  )
  PCTFREE 10 PCTUSED 40 TABLESPACE PROYECTO LOGGING STORAGE
  (
    INITIAL 1048576 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  ) ;

CREATE TABLE PROGRA2.FACTURAS_TABLE OF PROGRA2.FACTURACOMPRAS_TYPE
  (
    CODIGO NOT NULL ,
    CONSTRAINT FACTURAS_TABLE_PK PRIMARY KEY ( CODIGO )
  )
  PCTFREE 10 PCTUSED 40 TABLESPACE PROYECTO LOGGING STORAGE
  (
    INITIAL 1048576 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  NESTED TABLE LISTA_LINEASFACTURA STORE AS LISTA_LINEASFACTURA ;

CREATE TABLE PROGRA2.INDICES_ECONOMICOS_TABLE OF PROGRA2.INDICEECONOMICO_TYPE
  (
    DESCRIPCION NOT NULL ,
    CONSTRAINT INDICES_ECONOMICOS_TABLE_PK PRIMARY KEY ( DESCRIPCION )
  )
  PCTFREE 10 PCTUSED 40 TABLESPACE PROYECTO LOGGING STORAGE
  (
    INITIAL 1048576 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  NESTED TABLE LISTA_TIPOCAMBIOS STORE AS LISTA_TIPOCAMBIOS ;

CREATE TABLE PROGRA2.LISTAS_PRECIOS_TABLE OF PROGRA2.LISTAPRECIO_TYPE
  (
    DESCRIPCION NOT NULL ,
    CONSTRAINT LISTAS_PRECIOS_TABLE_PK PRIMARY KEY ( DESCRIPCION )
  )
  PCTFREE 10 PCTUSED 40 TABLESPACE PROYECTO LOGGING STORAGE
  (
    INITIAL 1048576 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  )
  NESTED TABLE LISTA_ARTICULOS STORE AS LISTA_ARTICULOS ;

CREATE TABLE PROGRA2.MONEDAS_TABLE OF PROGRA2.MONEDA_TYPE
  (
    DESCRIPCION NOT NULL ,
    CONSTRAINT MONEDAS_TABLE_PK PRIMARY KEY ( DESCRIPCION )
  )
  PCTFREE 10 PCTUSED 40 TABLESPACE PROYECTO LOGGING STORAGE
  (
    INITIAL 1048576 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  ) ;

CREATE TABLE PROGRA2.PERMISOS_TABLE OF PROGRA2.PERMISO_TYPE
  (
    DESCRIPCION NOT NULL ,
    CONSTRAINT PERMISOS_TABLE_PK PRIMARY KEY ( DESCRIPCION )
  )
  PCTFREE 10 PCTUSED 40 TABLESPACE PROYECTO LOGGING STORAGE
  (
    INITIAL 1048576 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  ) ;

CREATE TABLE PROGRA2.PROYECCIONES_TABLE OF PROGRA2.PROYECCION_TYPE
  (
    FECHA NOT NULL
  )
  PCTFREE 10 PCTUSED 40 TABLESPACE PROYECTO LOGGING STORAGE
  (
    INITIAL 1048576 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  ) ;

CREATE TABLE PROGRA2.TIPOS_CAMBIO_TABLE OF PROGRA2.TIPOCAMBIO_TYPE
  (
    FECHA NOT NULL
  )
  PCTFREE 10 PCTUSED 40 TABLESPACE PROYECTO LOGGING STORAGE
  (
    INITIAL 1048576 NEXT 1048576 PCTINCREASE 0 MINEXTENTS 1 MAXEXTENTS 2147483645 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
  ) ;

CREATE OR REPLACE TYPE BODY PROGRA2.PERMISO_TYPE
AS
  FINAL CONSTRUCTOR
FUNCTION PERMISO_TYPE(
    DESCRIPCION IN VARCHAR2 )
  RETURN SELF
AS
  RESULT
AS
  -- Empty PL/SQL Body
BEGIN
  NULL;
END;
END ;
/


-- Informe de Resumen de Oracle SQL Developer Data Modeler: 
-- 
-- CREATE TABLE                            19
-- CREATE INDEX                             0
-- ALTER TABLE                              0
-- CREATE VIEW                              0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         5
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   6
-- CREATE STRUCTURED TYPE                  28
-- CREATE STRUCTURED TYPE BODY              1
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        1
-- CREATE USER                              1
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
